In [ ]:
import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_array = np.ones((3,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
array = np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
sub_array = arr[3:8]
print(sub_array)

[4 5 6 7 8]


In [ ]:
random_array = np.random.randint(10, 50, size=(5, 5))  # 5x5 array with values between 10 and 50

extracted_rows = random_array[1:3, :]  # Extracting second and third rows (index 1 and 2)

print("Random 5x5 Array:\n", random_array)
print("\nExtracted Rows:\n", extracted_rows)

Random 5x5 Array:
 [[10 49 25 39 17]
 [11 40 49 35 20]
 [36 42 22 20 44]
 [34 19 22 35 37]
 [27 12 24 34 40]]

Extracted Rows:
 [[11 40 49 35 20]
 [36 42 22 20 44]]


In [ ]:
array1 = np.arange(1, 10).reshape(3, 3)

# Creating the second array with values from 10 to 18
array2 = np.arange(10, 19).reshape(3, 3)

# Element-wise addition
addition_result = array1 + array2

# Element-wise multiplication
multiplication_result = array1 * array2

print("First Array:\n", array1)
print("Second Array:\n", array2)
print("Element-wise Addition:\n", addition_result)
print("Element-wise Multiplication:\n", multiplication_result)

First Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Array:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Element-wise Addition:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Element-wise Multiplication:
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

modified_arr = (arr - 10) * 2

print("Modified Array:", modified_arr)

Modified Array: [ 0 20 40 60 80]


In [ ]:
#Create a random array of 20 elements with values between 1 and 100. Find the mean, median, and standard deviation of the array.
array = np.random.randint(1,101,20)
meanarr = np.mean(array)
medianarr = np.median(array)
stdarr = np.std(array)
print(array)
print(meanarr)
print(medianarr)
print(stdarr)

[97 25  2 93 97 87 53 20 64 12 40 57 82 31  4 64 96 82  3 47]
52.8
55.0
33.287535204637784


In [ ]:
# Generate a 4x4 matrix with random numbers and find the sum of all elements, sum of each row, and sum of each column
rando_arr = np.random.randint(1,101,(4,4))
total_sum = np.sum(rando_arr)
row_sums = np.sum(rando_arr, axis=1)
column_sums = np.sum(rando_arr, axis=0)

print("\nRandom 4x4 Matrix:\n", rando_arr)
print("Sum of all elements:", total_sum)
print("Sum of each row:", row_sums)
print("Sum of each column:", column_sums)


Random 4x4 Matrix:
 [[83 78 98 18]
 [18 79 60 81]
 [67 93 84 82]
 [87 86 64 90]]
Sum of all elements: 1168
Sum of each row: [277 238 326 327]
Sum of each column: [255 336 306 271]


In [ ]:
# Create a 1-dimensional array with 16 elements and reshape it into a 4x4 matrix.
array = np.arange(1,17).reshape(4,4)
print(array)
 #Given a 3x4 matrix, transpose the matrix to get a 4x3 matrix.
arr = np.arange(1,13).reshape(3,4)
arrt= arr.T
print(arrt)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
# Create an array a = np.array([1, 2, 3]) and an array b = np.array([[1], [2], [3]]). Perform element-wise multiplication of a and b using broadcasting.
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print(a)
print(b)
re = a*b
print(re)




[1 2 3]
[[1]
 [2]
 [3]]
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [ ]:
#Given the array arr = np.array([5, 12, 18, 24, 32]), create a boolean array that checks which elements are greater than 15.
arr = np.array([5, 12, 18, 24, 32])
bool_arr = arr > 15
print("Boolean Array:", bool_arr)
# Use the boolean array to extract the elements from arr that are greater than 15

filtered_arr = arr[bool_arr]
print("Filtered Elements:", filtered_arr)


Boolean Array: [False False  True  True  True]
Filtered Elements: [18 24 32]


In [ ]:
# Create an array with elements [1, 2, np.nan, 4, np.nan, 6]. Use NumPy functions to replace NaN values with the mean of the non-NaN elements.
arr = np.array([1, 2, np.nan, 4, np.nan, 6])
mean_value = np.nanmean(arr)
arr[np.isnan(arr)] = mean_value
print("Array replacing NaNs:", arr)
#Create an array [np.inf,-np.inf, 5,-7]. Replace positive infinity with 10 and negative infinity with-10
arr_inf = np.array([np.inf, -np.inf, 5, -7])
arr_inf[arr_inf == np.inf] = 10
arr_inf[arr_inf == -np.inf] = -10

print("Array after replacing infinities:", arr_inf)

Array replacing NaNs: [1.   2.   3.25 4.   3.25 6.  ]
Array after replacing infinities: [ 10. -10.   5.  -7.]


In [ ]:
#• Create a 1-dimensional array of 10 random integers between 1 and 100. Sort the array in ascending and descending order.
arr = np.random.randint(1,101,10)
arr_sort = np.sort(arr)
print(arr_sort)
#Given a 2-dimensional array, sort each row in ascending order.
arr_2d = np.random.randint(1,101,(3,3))
print("Original array:\n",arr_2d)
sorted_arr_2d = np.sort(arr_2d, axis=1)
print("\nSorted array (each row in ascending order):\n",sorted_arr_2d)


[ 5 21 23 23 38 60 75 89 90 96]
Original array:
 [[11 21 80]
 [88 39 97]
 [70 76 19]]

Sorted array (each row in ascending order):
 [[11 21 80]
 [39 88 97]
 [19 70 76]]


In [ ]:
#Create a 5x5 array of random integers between 1 and 20. Use advanced indexing to replace all elements greater than 10 with the value 10.
arr = np.random.randint(1,21,(5,5))
print(arr)
arrsor= arr > 10
print(arrsor)
corrarr = np.where(arr>10,10,arr)
print(corrarr)
#Create a 4x4 array of random values. Extract the corner elements using indexing.
ar = np.random.rand(4, 4)
top_left = ar[0, 0]
top_right = ar[0, -1]
bottom_left = ar[-1, 0]
bottom_right = ar[-1, -1]

print("Array:")
print(ar)
print("\nCorner elements:")
print("Top-left:", top_left)
print("Top-right:", top_right)
print("Bottom-left:", bottom_left)
print("Bottom-right:", bottom_right)

[[ 1 19  8  3  1]
 [19 12 19  6 15]
 [14  1  7  4  6]
 [ 3 11 12 16 14]
 [ 9  6  3 11 14]]
[[False  True False False False]
 [ True  True  True False  True]
 [ True False False False False]
 [False  True  True  True  True]
 [False False False  True  True]]
[[ 1 10  8  3  1]
 [10 10 10  6 10]
 [10  1  7  4  6]
 [ 3 10 10 10 10]
 [ 9  6  3 10 10]]
Array:
[[0.43614216 0.53507387 0.88648025 0.22665222]
 [0.24620603 0.23977283 0.28575388 0.35216035]
 [0.38123497 0.57245474 0.43817601 0.72742036]
 [0.58557478 0.5195785  0.5715528  0.78338903]]

Corner elements:
Top-left: 0.4361421584791503
Top-right: 0.2266522204080066
Bottom-left: 0.5855747762455208
Bottom-right: 0.7833890291802506
